# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-03-27 12:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phonenumber', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=100)),
                ('fathersname', models.CharField(max_length=30)),
                ('occupation', models.CharField(max_length=12)),
                ('vehiclenumber', models.CharField(max_length=11)),
                ('idproof', models.CharField(max_length=11)),
                ('rfid', models.CharField(max_length=11)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mobilenumber', models.CharField(max_length=12)),
                ('address_to_visit', models.TextField(max_length=256)),
                ('purpose_of_visit', models.CharField(max_length=500)),
                ('vehiclenumber', models.CharField(max_length=11)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 27, 18, 13, 17, 626296))),
                ('status', models.CharField(max_length=10)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.Resident')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mobilenumber', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=256)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.Resident')),
            ],
        ),
    ]
