# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-03-29 13:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_auto_20190329_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='rid',
            field=models.CharField(default=None, max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='visitor',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 29, 19, 2, 53, 979918)),
        ),
    ]
