# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-03-29 14:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_auto_20190329_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resident',
            name='id',
        ),
        migrations.AlterField(
            model_name='resident',
            name='rid',
            field=models.CharField(max_length=12, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 29, 19, 38, 50, 962536)),
        ),
    ]
