# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-03-29 15:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_auto_20190329_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 29, 20, 56, 36, 183604)),
        ),
    ]
