# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-04-01 14:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0007_auto_20190329_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='id',
        ),
        migrations.AddField(
            model_name='visitor',
            name='vid',
            field=models.CharField(default=None, max_length=12, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='visitor',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 4, 1, 20, 2, 27, 699793)),
        ),
    ]
