# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-04-01 14:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0009_auto_20190401_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='id',
        ),
        migrations.AddField(
            model_name='worker',
            name='wid',
            field=models.CharField(default=None, max_length=12, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='visitor',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 4, 1, 20, 21, 47, 877941)),
        ),
    ]
