# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-04-01 15:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0011_auto_20190401_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 4, 1, 20, 43, 57, 841091)),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 4, 1, 20, 43, 57, 842126)),
        ),
        migrations.AlterField(
            model_name='worker',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 4, 1, 20, 43, 57, 842126)),
        ),
    ]
