# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-04-08 08:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0021_auto_20190408_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 4, 8, 14, 2, 6, 973437)),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 4, 8, 14, 2, 6, 974435)),
        ),
        migrations.AlterField(
            model_name='worker',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 4, 8, 14, 2, 6, 975432)),
        ),
    ]
